version: '2'
services:
    ioa-app:
        image: ioa
        external_links:
            - ioa-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ioa
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ioa-postgresql:
        extends:
            file: postgresql.yml
            service: ioa-postgresql
